### ISSUE TITLE
Add DISPLAY support

### ISSUE THREAD

**Issue by Jonny999999** [Jonny999999/armchair_fw#12]
## todo hardware
- [x] modify joystick mount part
- [x] install display
- [x] rework mount: larger display

## todo software
- [x] search and test display driver
- [ ] fonts
- [ ] display bitmap

## features / ideas
- display stats
  - [x] display bat level
  - [x] display current
  - [ ] display temperature
  - [x] current / switch mode

- config menu
  - [ ] max speed
  - [ ] current limit
  - [x] joystick calibration
  - [x] max duty
  - [x] set accel limit
  - [x] set decel limit
  - [ ] preset slow mode ( see https://github.com/Jonny999999/armchair_fw/issues/14 )
    - [ ] low max duty
    - [ ] low accel/decel
  - [x] reset settings (load defaults to eeprom) and restart?
  - [x] restart
