### ISSUE TITLE
joystick control: optimize turn behavior

### ISSUE THREAD

**Issue by Jonny999999** [Jonny999999/armchair_fw#13]
## issue
currently making a hard turn using joystick in any quadrant seems weird / is almost not possible  
thus changing to full turn mode (wheels in opposite direction) is usually necessary.

- at low angle (Y almost at 0) radius is not 1? noticed outer wheel slowing down compared to at 45Deg max radius

## ideas
- set inner wheel duty to 0 earlier, this could optimize turning radius
- increase outer wheel duty above configured duty limit (95)

## tasks
- [x]  test whether radius is not read 1 at low angles
  - wass issue due to wrong scaling
  - fixed in d715f2e0f1c82c65daf3b925532eddbb9e1ac62b
- [x] add threshold for joystick angle where the ratio snaps to 0
  - implemented in ffbf9ccec8574f791fef27001836568f5d1ed3f8
  - needs to be enabled later, see https://github.com/Jonny999999/armchair_fw/issues/19
  - now reworked and implemented  in a6a630af44375add046985b84c615ead8bba3610
- [x] boost duty of outer tire https://github.com/Jonny999999/armchair_fw/issues/19  - added in a6a630af44375add046985b84c615ead8bba3610
- [ ] more responsive
  - see https://github.com/Jonny999999/armchair_fw/issues/21
