### ISSUE TITLE
motor driver freezes at duty restart

### ISSUE THREAD

**Issue by Jonny999999** [Jonny999999/armchair_fw#18]
very annoying bug with motor driver:
sometimes a motor seemingly randomly freezes for a few seconds, then immediately starts at current set duty again - feels very bugged

especially when trying to add angle threshold (snap to 1 / 0)  for tighter turn radius so one motor is off while turning
this bug basically occurs every time -> inner motor does not start again after curve

## current workaround
when 1 motor frozen, release joystick so both motors are off, then go again

### best for testing: 
- turn deceleration off (8x button press)
- forward, release, forward again

### common situations
1. both motors forward
2. motor1 duty to 0
3. motor1 duty positive
   ==> motor1 freezes / stays off
   ==> after a few seconds it starts

4. both motors to 0
5. both motors forward
  ==> both motors respond again

-------
1. both motors forward
2. both motors 0
3. both motors forward
   => one or both motor freeze for (shorter than usual) time then start at current duty

## ideas / theories
- A, B driver signal gets noise from other running driver?
- bug with driver getting confused by stopped duty
  - not likely, see tests
- signals affect each other because with common diode and pullup at mosfet pins

## things tried
    - leave duty on in idle
    - never switch do idle
    - always stay in FWD with some duty on
    - reduce max duty to 60%

same issue persists
1 motor gets close to 0 duty while other is on it freezes

## todo
- [x] take of chair and measure with oscilloscope
  - measure actual voltage at A, B pins
  - measure acutal pwm signal
- [x] search the internet for issues with thos drivers 
- [ ] implement workaround?
  - [x] detect situation when motor gets to 0 duty and restarts, 
  - [x] stop other motor too for 100ms 
  - [x] restart at previous duty immediately
