### ISSUE TITLE
[V2.1] UART | broadcast config, update config functionality

### ISSUE THREAD

**Issue by Jonny999999** [Jonny999999/armchair_fw#23]
due to separate boards
changes in configuration of motorctl have to be sent via uart to the motorctl board

## tasks to restore V2.0 functionality
the controlledmotor objects are no longer accessable directly thus certain features were disabled and need rework
- [ ] control.cpp 'changeMode' 
  - [ ] switch from MASSAGE enables fading
  - [ ] (switch from AUTO enables fading)
  - [ ] switch to MASSAGE disables fading 
- [ ] button.cpp
  - [ ] case 8: toggle fading

## tasks
- [ ] motorctl board: repeatedly boradcast current active config 
- [ ] motorctl board: receive and update config
  - [ ] add method to update or refresh config in object
- [ ] control board: store current config
- [ ] control board: method to modify and update config
