### ISSUE TITLE
chair-adjustment control via joystick

### ISSUE THREAD

**Issue by Jonny999999** [Jonny999999/armchair_fw#32]
original char adjustmen electronic broke down 3 time by now
=> replace it with custom control

# ideas
- use free 4x mosfet outputs
- use joystick as control interface
- ~h-bridge?~
- relay board
- connector
  - additional connector (6 pins) required 
  - upgrade existin 9pin subD? -> not practical due to wiring in armchair

# tasks
- [x] update connection plan
  - [x] schematic
  - [x] connection to board
  - [x] wiring 3d-model box?
- [x] housing for relays on armchair
- [x] new connector
- [x] test relays (inverted?) -> pullup?
- [x] firmware
  - [x] implement adjust mode
