### ISSUE TITLE
Todo HARDWARE

### ISSUE THREAD

**Issue by Jonny999999** [Jonny999999/armchair_fw#36]
Task list for hardware changes
# Ideas
- [ ] Attachments (power outlet, frame mount):
  - [ ] detachable ventilator
  - [ ] detachable lamp
- [ ] integrate wireless phone charging

 
# Fixes when armchair is detached:
- [x] switch sometimes not working (box warm)  fix most likely unreliable contact on pcb (=> screw terminal was ripped off due to torque, replaced, added wire)
- [x] swap right motor to be quiet too
- [x] change gear ratio from Z10 / Z14  to both 12 (=> changed to Z16, topspeed ~10km/h)
- oscilloscope
  - [x] debug speed sensors (inspect signal with oscilloscope) (=> looks fine, probably issue due to previously too high cpu load)
  - [x] debug encoder left rotation slow (=> Fixed with adding missing 3v3 Z-Diode)
  - [x] analyse stick signal (see https://github.com/Jonny999999/armchair_fw/issues/37 ) (=> added hardware filter see con-plan)
    - [x] add hardware filter?
- [x] replace original chair board with relay board for chair adjustment
  - [x] design and print box
  - [x] update wiring plan
  - [x] wire relay box, PS2 cable
  - [x] integrate into armchair
- [x] replace broken left encoder mount
  - [x] optimize design (mirrored not enough)
  - [x] print using PETG, mount with washers
- [x] UI-Arm
  - [x] print again using PLA (less bending) (=> noticed no significant difference between the PLA vs PETG)
  - [x] change design
    - [x] larger display
    - [x] no thin wall above thisplay
  - [x] install large display
  - [x] install new stick 

# General issues
- [x] inspect front right tire (clicking sound at each rotation) (=> built custom axle with less play and more grease)
- [ ] when driving reverse with weight on left side there is grinding noise with spring of chair mechanism at left motor
      => linkage of armchair adjustment comes in contact with nut on motor shaft, when chair in certain position and suspension far down, happens at both sides  ->  no idea how to fix this right now
  - [ ] add limit stop gummy-buffer to prevent this collision
