### ISSUE TITLE
Simplify nvs read/write functions (remove duplicate code)

### ISSUE THREAD

**Issue by Jonny999999** [Jonny999999/armchair_fw#48]
Currently two separate functions are preset for **each** variable stored persistently in nvs. That results in a significant amount of duplicate code!

## tasks
- [ ] add general function to read a value and/or copy a default value
- [ ] add general function to write a value
- [ ] apply functions where possible
- [ ] remove redundant code

Pass string to storage and pointers to default and target value?
