### ISSUE TITLE
Messed up driving behavior: evaluate and adjust config parameters

### ISSUE THREAD

**Issue by Jonny999999** [Jonny999999/armchair_fw#52]
Adjusting newly added options needs alot of testing when driving is possible

# Issues 
- slow movements are not really possib
- turns too fast

# tasks
## static config options
- [ ] define optimal joystick scaling point
- [ ] define optimal duty-boost scaling modifier

## dynamic options
- [ ] optimize default accel/decel
- [ ] optimize default boost
- [ ] optimize default max-duty (lower)
